version: "3.4"

services:
  dev-serve:
    image: dev-serve
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080
      - 8080:8080
    command: ["node", "--inspect=0.0.0.0:8080", "app.js"]
